<?php

/**
 * @file
 * Contains helfi_tpr.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function helfi_tpr_theme() {
  return [
    'tpr_accessibility_sentences' => [
      'variables' => ['name' => NULL, 'items' => []],
    ],
    'tpr_unit' => [
      'render element' => 'elements',
      'template' => 'tpr-unit',
    ],
    'tpr_service' => [
      'render element' => 'elements',
      'template' => 'tpr-service',
    ],
    'tpr_unit_form' => [
      'render element' => 'form',
    ],
    'tpr_service_form' => [
      'render element' => 'form',
    ],
    'tpr_service_channel' => [
      'render element' => 'elements',
      'template' => 'tpr-service-channel'
    ],
    'tpr_errand_service' => [
      'render element' => 'elements',
      'template' => 'tpr-errand-service'
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function helfi_tpr_theme_suggestions_tpr_unit(array $variables) {
  $suggestions = [];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'tpr_unit__' . $sanitized_view_mode;

  return $suggestions;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function helfi_tpr_theme_suggestions_tpr_service(array $variables) {
  $suggestions = [];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'tpr_service__' . $sanitized_view_mode;

  return $suggestions;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function helfi_tpr_theme_suggestions_tpr_service_channel(array $variables) {
  $suggestions = [];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'tpr_service_channel__' . $sanitized_view_mode;

  return $suggestions;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function helfi_tpr_theme_suggestions_tpr_errand_service(array $variables) {
  $suggestions = [];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'tpr_errand_service__' . $sanitized_view_mode;

  return $suggestions;
}

/**
 * Prepares variables for tpr_unit templates.
 *
 * Default template: tpr-unit.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An array of elements to display in view mode.
 */
function template_preprocess_tpr_unit(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  // Helpful $content variable for templates.
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
  if (isset($variables['elements']['#tpr_unit'])) {
    $variables['entity'] = $variables['elements']['#tpr_unit'];
    $variables['content']['description_summary'] = $variables['elements']['#tpr_unit']->get('description')->summary;
  }
  // Get provided languages for the template.
  $provided_languages = $variables['elements']['#tpr_unit']->get('provided_languages')->getValue();

  foreach ($provided_languages as $provided_language) {
    $variables['provided_languages'][] = $provided_language['value'];
  }
}

/**
 * Prepares variables for tpr_unit templates.
 *
 * Default template: tpr-unit.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An array of elements to display in view mode.
 */
function template_preprocess_tpr_service(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  // Helpful $content variable for templates.
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
  if (isset($variables['elements']['#tpr_service'])) {
    $variables['entity'] = $variables['elements']['#tpr_service'];
    $variables['content']['description_summary'] = $variables['elements']['#tpr_service']->get('description')->summary;
  }
}

/**
 * Prepares variables for tpr_service_channel templates.
 *
 * Default template: tpr-service-channel.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An array of elements to display in view mode.
 */
function template_preprocess_tpr_service_channel(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  // Helpful $content variable for templates.
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
  if (isset($variables['elements']['#tpr_service_channel'])) {
    $variables['entity'] = $variables['elements']['#tpr_service_channel'];
    //$variables['content']['description_summary'] = $variables['elements']['#tpr_service_channel']->get('description')->summary;
  }
}

/**
 * Prepares variables for tpr_errand_service templates.
 *
 * Default template: tpr-errand-service.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An array of elements to display in view mode.
 */
function template_preprocess_tpr_errand_service(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  // Helpful $content variable for templates.
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
  if (isset($variables['elements']['#tpr_errand_service'])) {
    $variables['entity'] = $variables['elements']['#tpr_errand_service'];
    //$variables['content']['description_summary'] = $variables['elements']['#tpr_service_channel']->get('description')->summary;
  }
}
