helfi_tpr.migration_settings.*:
  type: mapping
  label: TPR migration settings
  mapping: &base
    langcode:
      type: string
      label: Langcode
    canonical_url:
      type: string
      label: Canonical URL
    url:
      type: string
      label: Url

field.value.accessibility_sentence:
  type: mapping
  label: Default value
  mapping:
    group:
      label: Group
      type: string
    value:
      type: string
      label: Value

field.formatter.settings.tpr_service_channel_formatter:
  type: mapping
  mapping:
    view_mode:
      type: string
      label: 'View mode'
    link:
      type: boolean
      label: 'Show links'
    sort_order:
      type: sequence
      sequence:
        type: mapping
        mapping:
          weight:
            type: integer

field.formatter.settings.service_map_embed:
  type: mapping
  label: 'Service map embed'
  mapping:
    iframe_title:
      type: label
      label: 'Iframe title'
    link_title:
      type: label
      label: 'Link title'
    target:
      type: boolean
      label: 'Whether to open in a new tab or not'

field.value.tpr_connection:
  type: mapping
  label: Default value
  mapping:
    type:
      type: label
      label: Type
    value:
      type: label
      label: Value
