views.view.service_units:
  expected_config:
    display:
      default:
        display_options:
          filters:
            content_translation_status:
              admin_label: ''
              entity_field: content_translation_status
              entity_type: tpr_unit
              expose:
                description: ''
                identifier: ''
                label: ''
                multiple: false
                operator: ''
                operator_id: ''
                operator_limit_selection: false
                operator_list: {  }
                remember: false
                remember_roles:
                  authenticated: authenticated
                required: false
                use_operator: false
              exposed: false
              field: content_translation_status
              group: 1
              group_info:
                default_group: All
                default_group_multiple: {  }
                description: ''
                group_items: {  }
                identifier: ''
                label: ''
                multiple: false
                optional: true
                remember: false
                widget: select
              group_type: group
              id: content_translation_status
              is_grouped: false
              operator: '='
              plugin_id: boolean
              relationship: none
              table: tpr_unit_field_data
              value: '1'
          pager:
            options:
              items_per_page: 8
          row:
            options:
              view_mode: teaser
        display_title: Master
  update_actions:
    delete:
      display:
        default:
          display_options:
            filters:
              content_translation_status:
                admin_label: ''
                entity_field: content_translation_status
                entity_type: tpr_unit
                expose:
                  description: ''
                  identifier: ''
                  label: ''
                  multiple: false
                  operator: ''
                  operator_id: ''
                  operator_limit_selection: false
                  operator_list: {  }
                  remember: false
                  remember_roles:
                    authenticated: authenticated
                  required: false
                  use_operator: false
                exposed: false
                field: content_translation_status
                group: 1
                group_info:
                  default_group: All
                  default_group_multiple: {  }
                  description: ''
                  group_items: {  }
                  identifier: ''
                  label: ''
                  multiple: false
                  optional: true
                  remember: false
                  widget: select
                group_type: group
                id: content_translation_status
                is_grouped: false
                operator: '='
                plugin_id: boolean
                relationship: none
                table: tpr_unit_field_data
                value: '1'
    add:
      display:
        default:
          cache_metadata:
            contexts:
              - user
          display_options:
            filters:
              status_extra:
                admin_label: ''
                entity_type: tpr_unit
                expose:
                  description: ''
                  identifier: ''
                  label: ''
                  multiple: false
                  operator: ''
                  operator_id: ''
                  operator_limit_selection: false
                  operator_list: {  }
                  remember: false
                  remember_roles:
                    authenticated: authenticated
                  required: false
                  use_operator: false
                exposed: false
                field: status_extra
                group: 1
                group_info:
                  default_group: All
                  default_group_multiple: {  }
                  description: ''
                  group_items: {  }
                  identifier: ''
                  label: ''
                  multiple: false
                  optional: true
                  remember: false
                  widget: select
                group_type: group
                id: status_extra
                is_grouped: false
                operator: '='
                plugin_id: tpr_status
                relationship: none
                table: tpr_unit_field_data
                value: ''
            sorts:
              name:
                expose:
                  field_identifier: name
              name_override:
                expose:
                  field_identifier: name_override
        service_units:
          cache_metadata:
            contexts:
              - user
    change:
      display:
        default:
          display_options:
            pager:
              options:
                items_per_page: 5
            row:
              options:
                view_mode: teaser_with_image
          display_title: Default
views.view.unit_services:
  expected_config:
    display:
      default:
        display_options:
          filters:
            content_translation_status:
              admin_label: ''
              entity_field: content_translation_status
              entity_type: tpr_service
              expose:
                description: ''
                identifier: ''
                label: ''
                multiple: false
                operator: ''
                operator_id: ''
                operator_limit_selection: false
                operator_list: {  }
                remember: false
                remember_roles:
                  authenticated: authenticated
                required: false
                use_operator: false
              exposed: false
              field: content_translation_status
              group: 1
              group_info:
                default_group: All
                default_group_multiple: {  }
                description: ''
                group_items: {  }
                identifier: ''
                label: ''
                multiple: false
                optional: true
                remember: false
                widget: select
              group_type: group
              id: content_translation_status
              is_grouped: false
              operator: '='
              plugin_id: boolean
              relationship: services_target_id
              table: tpr_service_field_data
              value: '1'
          pager:
            options:
              items_per_page: 4
        display_title: Master
  update_actions:
    delete:
      display:
        default:
          display_options:
            filters:
              content_translation_status:
                admin_label: ''
                entity_field: content_translation_status
                entity_type: tpr_service
                expose:
                  description: ''
                  identifier: ''
                  label: ''
                  multiple: false
                  operator: ''
                  operator_id: ''
                  operator_limit_selection: false
                  operator_list: {  }
                  remember: false
                  remember_roles:
                    authenticated: authenticated
                  required: false
                  use_operator: false
                exposed: false
                field: content_translation_status
                group: 1
                group_info:
                  default_group: All
                  default_group_multiple: {  }
                  description: ''
                  group_items: {  }
                  identifier: ''
                  label: ''
                  multiple: false
                  optional: true
                  remember: false
                  widget: select
                group_type: group
                id: content_translation_status
                is_grouped: false
                operator: '='
                plugin_id: boolean
                relationship: services_target_id
                table: tpr_service_field_data
                value: '1'
    add:
      display:
        default:
          cache_metadata:
            contexts:
              - user
          display_options:
            filters:
              status_extra:
                admin_label: ''
                entity_type: tpr_service
                expose:
                  description: ''
                  identifier: ''
                  label: ''
                  multiple: false
                  operator: ''
                  operator_id: ''
                  operator_limit_selection: false
                  operator_list: {  }
                  remember: false
                  remember_roles:
                    authenticated: authenticated
                  required: false
                  use_operator: false
                exposed: false
                field: status_extra
                group: 1
                group_info:
                  default_group: All
                  default_group_multiple: {  }
                  description: ''
                  group_items: {  }
                  identifier: ''
                  label: ''
                  multiple: false
                  optional: true
                  remember: false
                  widget: select
                group_type: group
                id: status_extra
                is_grouped: false
                operator: '='
                plugin_id: tpr_status
                relationship: services_target_id
                table: tpr_service_field_data
                value: ''
            sorts:
              name:
                expose:
                  field_identifier: name
              name_override:
                expose:
                  field_identifier: name_override
        unit_services:
          cache_metadata:
            contexts:
              - user
    change:
      display:
        default:
          display_options:
            pager:
              options:
                items_per_page: 8
          display_title: Default
