on: [push]
name: CI
env:
  SIMPLETEST_DB: "mysql://drupal:drupal@db:3306/drupal"
  SIMPLETEST_BASE_URL: "http://127.0.0.1:8080"
  MODULE_NAME: helfi_tpr
  SYMFONY_DEPRECATIONS_HELPER: disabled
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.0']
    container:
      image: ghcr.io/city-of-helsinki/drupal-php-docker:${{ matrix.php-versions }}

    services:
      db:
        image: druidfi/db:mysql5.7-drupal
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set variables
        run: |
          echo "DRUPAL_ROOT=$HOME/drupal" >> $GITHUB_ENV

      - name: Build project
        run: |
          composer create-project city-of-helsinki/drupal-helfi-platform:dev-main $DRUPAL_ROOT --no-interaction --repository https://repository.drupal.hel.ninja/
          cd $DRUPAL_ROOT
          php -d sendmail_path=$(which true); vendor/bin/drush --yes -v site-install minimal --db-url="$SIMPLETEST_DB"
          composer config repositories.2 path $GITHUB_WORKSPACE
          composer require drupal/$MODULE_NAME
          vendor/bin/drush en $MODULE_NAME -y

      - name: Run PHPCS
        run: cd $DRUPAL_ROOT && composer lint-php public/modules/contrib/$MODULE_NAME

      #- name: Run PHPStan
      #  run: cd $DRUPAL_ROOT && php -d memory_limit=-1 vendor/bin/phpstan --level=5 analyze public/modules/contrib/$MODULE_NAME --no-progress

      - name: Run PHPUnit tests
        run: |
          cd $DRUPAL_ROOT
          vendor/bin/drush runserver $SIMPLETEST_BASE_URL > /dev/null 2>&1 &
          chromedriver --port=4444 > /dev/null 2>&1 &
          vendor/bin/phpunit -c $DRUPAL_ROOT/phpunit.platform.xml --verbose public/modules/contrib/$MODULE_NAME
